apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: redis-pod
    # this is the name of whole application
    app: demo-voting-app
spec:
  containers:
    - name: redis
      image: redis:latest
      ports:
        - containerPort: 6379
